--DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER`
(
    `MEMBER_KEY`            bigint              NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    `MEMBER_ID`             varchar(30)         NOT NULL unique,
    `PASSWORD`              varchar(300)        NOT NULL,
    `MEMBER_NM`             varchar(30)         NOT NULL,
    `REG_NO`                varchar(300)        NOT NULL unique,
    `CREATE_DT`             date                NOT NULL,
    `LAST_MODIFY_DT`        date                NOT NULL,
    PRIMARY KEY (`MEMBER_KEY`)
);








